[package]
name = "mini-bitcask"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2"
serde = {version = "1", features = ["derive"]}
tokio = {version = "1", features = ["full"]}
console-subscriber = "0.1"
clap = "4.5.37"
